export const SUBSECTION_SELECTED = 'subsection.SUBSECTION_SELECTED';
export const SUBSECTION_STEPS_FETCHED = 'subsection.SUBSECTION_STEPS_FETCHED';

export const WEBSOCKET_OPENED = 'ws.WEBSOCKET_OPEN';
export const WEBSOCKET_CLOSED = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_MESSAGE = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_CONNECT = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_DISCONNECT = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_SEND = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCET_OPPEND = 'ws.WEBSOCKET_CLOSED';

export const RESPONSE_RECEIVED = 'ws.RESPONSE_RECEIVED';
