export const DEBUG = process.env.NODE_ENV === 'development';

export const LEARNINGMAP_SECTIONS_FETCHED = 'learningmap.LEARNINGMAP_SECTIONS_FETCHED';

export const SUBSECTION_SELECTED = 'subsection.SUBSECTION_SELECTED';
export const SUBSECTION_STEPS_FETCHED = 'subsection.SUBSECTION_STEPS_FETCHED';

export const WEBSOCKET_OPENED = 'ws.WEBSOCKET_OPEN';
export const WEBSOCKET_CLOSED = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_MESSAGE = 'ws.WEBSOCKET_MESSAGE';
export const WEBSOCKET_CONNECT = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_DISCONNECT = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCKET_SEND = 'ws.WEBSOCKET_CLOSED';
export const WEBSOCET_OPPEND = 'ws.WEBSOCKET_CLOSED';

export const RESPONSE_RECEIVED = 'ws.RESPONSE_RECEIVED';

export const VK_INIT = 'VK_APP/VK_INIT';

export const VK_GET_USER_INFO_REQUEST = 'VK_APP/VK_GET_USER_INFO_REQUEST';
export const VK_GET_USER_INFO_FETCHED = 'VK_APP/VK_GET_USER_INFO_FETCHED';
export const VK_GET_USER_INFO_FAILED = 'VK_APP/VK_GET_USER_INFO_FAILED';

export const USER_PROFILE_FETCHED = 'user.USER_PROFILE_FETCHED';
export const USER_NEW_STATE_FETCHED = 'user.USER_NEW_STATE_FETCHED';
